#ifndef MENU_HEADER_H_INCLUDED
#define MENU_HEADER_H_INCLUDED

#define ID 1
#define MY_LINE_PARAMETRIC 2
#define MY_LINE_NAIIVE 3
#define MY_LINE_SIMPLE_DDA 4
#define MY_LINE_INT_DDA  5
#define MY_LINE_MIDPOINT 6
#define MY_CIRCLE_DIRECT 7
#define MY_CIRCLE_PARAMETRIC 8
#define MY_CIRCLE_PARAMETRIC8 9
#define MY_CIRCLE_ITERATIVE 10
#define MY_CIRCLE_MIDPOINT1 11
#define MY_CIRCLE_MIDPOINT2 12
#define MY_ELLIPSE_DIRECT 13
#define MY_ELLIPSE_POLAR_NO 14
#define MY_ELLIPSE_POLAR_YES 15
#define MY_ELLIPSE_MIDPOINT 16
#define MY_QUADRATIC_CURVE 17
#define MY_BEZIER_QUADRATIC_CURVE 18
#define MY_HERMITE_CURVE 19
#define MY_BEZIER_CURVE1 20
#define MY_BEZIER_CURVE2 21
#define MY_SPLINES 22
#define MY_CLIPPING 23
#define MY_SAVE 25
#define MY_LOAD 26
#define MY_EXIT 27

#endif
